- alias: Enable light control by kokodi in the evening
  trigger:
    platform: time
    seconds: 0
    minutes: 0
    hours: 18
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.light_control_by_kokodi
- alias: Disable light control by kokodi in the evening
  trigger:
    platform: time
    seconds: 0
    minutes: 0
    hours: 1
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.light_control_by_kokodi


- alias: Activate movie playing scene
  trigger:
    platform: state
    entity_id: media_player.kokodi
    to: playing
  condition:
    - condition: state
      entity_id: input_boolean.light_control_by_kokodi
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.movie_playing
- alias: Activate movie paused scene
  trigger:
    platform: state
    entity_id: media_player.kokodi
    from: playing
    to: paused
  condition:
    - condition: state
      entity_id: input_boolean.light_control_by_kokodi
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.movie_paused
- alias: Activate movie stopped scene
  trigger:
    platform: state
    entity_id: media_player.kokodi
    to: idle
  condition:
    - condition: state
      entity_id: input_boolean.light_control_by_kokodi
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.movie_stopped

- alias: WakeUp routine
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - condition: state
      entity_id: group.all_devices #FIXME all devices is not the right marker (think kokodi, rougepom devices for instance)
      state: home
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: light.turn_on
    entity_id: group.sdb_parents
    data:
      brightness: 20

- alias: Start timer whenever light is turned on
  trigger:
    platform: state
    entity_id: group.sdb_parents
    to: 'on'
  action:
    service: timer.start
    entity_id: timer.sdb_light


- alias: Switch off bathroom after some time
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.sdb_light
  action:
    service: light.turn_off
    entity_id: group.sdb_parents

- alias: Turn on music when dash button is pressed (day)
  trigger:
    platform: event
    event_type: device_lease_44:65:d:b:aa:e6 # amazon dash "simple human"
  condition:
    - condition: time
      after: '07:00:00' # avoid night errors
      before: '19:30:00'
    - condition: state
      entity_id: media_player.kokodi
      state: idle
  action:
    service: shell_command.radio_swiss_classic

- alias: Play/Pause kodi when dash button pressed (evening)
  trigger:
    platform: event
    event_type: device_lease_44:65:d:b:aa:e6 # amazon dash "simple human"
  condition:
    - condition: time
      after: '19:30:00'
      before: '00:00:00'
  action:
    service: media_player.media_play_pause
    entity_id: media_player.kokodi
